### ISSUE TITLE
panic: applier must have 1 input parameter assignable from []fastly.TlsSubscriptionManagedDnsChallenge

### ISSUE THREAD

**Issue by Harry-027** [pulumi/pulumi-fastly#177]
### What happened?

ManagedDnsChallenges field on struct TlsSubscription has a wrong type. Following method invocation - 
`
subscription.ManagedDnsChallenges.ApplyT(func(challenges []fastly.TlsSubscriptionManagedDnsChallengeArrayOutput) pulumi.StringArray {}))`

throws an error -
`panic: applier must have 1 input parameter assignable from []fastly.TlsSubscriptionManagedDnsChallenge  `

However ManagedDnsChallenges has type `TlsSubscriptionManagedDnsChallengeArrayOutput` and applier throwing validation error for type `TlsSubscriptionManagedDnsChallenge`

### Steps to reproduce

1) Create a new TlsSubscription -
`  var subscription = NewTlsSubscription(args)`

2) Call `applyT` on ManagedDnsChallenges -
`
subscription.ManagedDnsChallenges.ApplyT(func(challenges []fastly.TlsSubscriptionManagedDnsChallengeArrayOutput) pulumi.StringArray {}))`

### Expected Behavior

It shouldn't throw error for `TlsSubscriptionManagedDnsChallengeArrayOutput` type

### Actual Behavior

panic: applier must have 1 input parameter assignable from []fastly.TlsSubscriptionManagedDnsChallenge

### Versions used

CLI          
Version      3.35.3
Go Version   go1.18.3
Go Compiler  gc

Host     
OS       darwin
Version  12.4
Arch     x86_64

Dependencies:
NAME                                                              VERSION
github.com/pulumi/pulumi-aws/sdk/v4          v4.38.1
github.com/pulumi/pulumi-cloudflare/sdk/v3   v3.6.0
github.com/pulumi/pulumi-fastly/sdk/v4       v4.0.4
github.com/pulumi/pulumi/sdk/v3              v3.34.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
Hi @Harry-027. I believe you want something of this form:
```
subscription.ManagedDnsChallenges.ApplyT(func(challenges []fastly.TlsSubscriptionManagedDnsChallenge) pulumi.StringArray {
....
}))
```

What validation error are you hitting when you say the following?
> and applier throwing validation error for type `TlsSubscriptionManagedDnsChallenge`

**Comment by Harry-027** [comment]
Hi @viveklak , it actually panics. I was considering type `TlsSubscriptionManagedDnsChallengeArrayOutput` in the closure method but you are correct it should be `TlsSubscriptionManagedDnsChallenge`. I will close the issue. Thanks 👍🏻
